// TODO: replace ALL_PLAYERS with real data fetched from Firebase
//import { displayName } from '../../utils'

const GRADIENTS = [
  'linear-gradient(135deg,#f5c518,#ef4444)',
  'linear-gradient(135deg,#10b981,#3b82f6)',
  'linear-gradient(135deg,#ec4899,#8b5cf6)',
  'linear-gradient(135deg,#f59e0b,#ef4444)',
  'linear-gradient(135deg,#4d9fff,#a855f7)',
  'linear-gradient(135deg,#6366f1,#ec4899)',
  'linear-gradient(135deg,#10b981,#f59e0b)',
  'linear-gradient(135deg,#f59e0b,#10b981)',
]

// [firstName, nickname (optional), lastName]
const NAMES = [
  ['Marcus', 'Bull',     'Green'],
  ['Tom',    '',         'Larson'],
  ['Noa',    'Flash',    'Rosen'],
  ['Jake',   '',         'Kim'],
  ['Ryan',   'Rocket',   'Davies'],
  ['Sofia',  '',         'Vasquez'],
  ['Alex',   'Gunner',   'Kowalski'],
  ['Luca',   '',         'Bianchi'],
  ['Grace',  'Panther',  'Nkosi'],
  ['Pavel',  '',         'Horak'],
  ['Mei',    'Swift',    'Tanaka'],
  ['Omar',   '',         'Hassan'],
  ['Elena',  'Viper',    'Petrov'],
  ['Carlos', '',         'Ruiz'],
  ['Amira',  'Ghost',    'Diallo'],
  ['Ben',    '',         'Fletcher'],
  ['Yuki',   'Storm',    'Saito'],
  ['Fatima', '',         'Al-Amin'],
  ['Ivan',   'Bear',     'Kozlov'],
  ['Sara',   '',         'Lindqvist'],
  ['Kwame',  'King',     'Asante'],
  ['Diana',  '',         'Moreau'],
  ['Raj',    'Blaze',    'Patel'],
  ['Chloe',  '',         'Martin'],
  ['Andrei', 'Wolf',     'Popescu'],
  ['Hana',   '',         'Suzuki'],
  ['Marco',  'Striker',  'Silva'],
  ['Ingrid', '',         'Holm'],
  ['Zara',   'Falcon',   'Ahmed'],
  ['Felix',  '',         'Wagner'],
  ['Priya',  'Spark',    'Sharma'],
  ['Louis',  '',         'Dubois'],
  ['Aisha',  'Arrow',    'Bello'],
  ['Dmitri', '',         'Volkov'],
  ['Clara',  'Ice',      'Jensen'],
  ['Ahmed',  '',         'Khalil'],
  ['Mia',    'Tempo',    'Johansson'],
  ['Tariq',  '',         'Nasser'],
  ['Emma',   'Ace',      'Wilson'],
  ['Seun',   '',         'Adeyemi'],
  ['Vlad',   'Shadow',   'Stanescu'],
  ['Leila',  '',         'Hosseini'],
  ['Baptiste','Cannon',  'Laurent'],
  ['Yuna',   '',         'Park'],
  ['Tobias', 'Tank',     'Muller'],
  ['Chioma', '',         'Obi'],
  ['Radu',   'Eagle',    'Ionescu'],
  ['Nina',   '',         'Kovac'],
  ['Hassan', 'Dagger',   'Diop'],
  ['Astrid', '',         'Berg'],
]

export const ALL_PLAYERS = NAMES.map(([firstName, nickname, lastName], i) => ({
  firstName,
  nickname,
  lastName,
  stars: Math.round(Math.max(1, 210 - i * 1.7 + (Math.random() * 4 - 2))),
  games: Math.round(Math.max(1, 45 - i * 0.35 + (Math.random() * 4 - 2))),
  grad: GRADIENTS[i % GRADIENTS.length],
  isYou: i === 6,
})).sort((a, b) => b.stars !== a.stars ? b.stars - a.stars : b.games - a.games)
